ammended updatUI
- when trying to npm run build-prod, I was getting following error:

ERROR in ./src/client/js/updateUI.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\anna.grohova\Documents\travel-app\src\client\js\updateUI.js: Identifier 'lat' has already been declared. (59:30)

  57 | //getting weather data from local endpoint
  58 |
> 59 | async function getWeatherData(lat, lng){
     |                               ^
  60 |     const lat = geoNamesData.lat;
  61 |     const lng = geoNamesData.lng;

so I figured I'd have to delete the lat, lng declaration